egrep "\bTS" ../inputs/input5.txt | egrep "55 |55-" | egrep "O$"
# echo a
egrep "\bTS" ../inputs/input5.txt | egrep "55 |55-" | egrep "0$"
# echo b
egrep "\bTS" ../inputs/input5.txt | egrep "SS |SS-" | egrep "O$"
# echo c
egrep "\bTS" ../inputs/input5.txt | egrep "SS |SS-" | egrep "0$"
# echo d
#	egrep "\bTS" ../inputs/input5.txt | egrep "555" | egrep "O$"
#	egrep "\bTS" ../inputs/input5.txt | egrep "555" | egrep "0$"
	# egrep "\bTS" ../inputs/input5.txt | egrep "SSS" | egrep "O$"
	# egrep "\bTS" ../inputs/input5.txt | egrep "SSS" | egrep "0$"
	# egrep "\bTS" ../inputs/input5.txt | egrep "5S" | egrep "O$"
	# egrep "\bTS" ../inputs/input5.txt | egrep "S5" | egrep "0$"
	# egrep "\bTS" ../inputs/input5.txt | egrep "55S" | egrep "O$"
	# egrep "\bTS" ../inputs/input5.txt | egrep "55S" | egrep "0$"
	# egrep "\bTS" ../inputs/input5.txt | egrep "5S5" | egrep "O$"
	# egrep "\bTS" ../inputs/input5.txt | egrep "5S5" | egrep "0$"
	# egrep "\bTS" ../inputs/input5.txt | egrep "S55" | egrep "O$"
	# egrep "\bTS" ../inputs/input5.txt | egrep "S55" | egrep "0$"
	# egrep "\bTS" ../inputs/input5.txt | egrep "5SS" | egrep "O$"
	# egrep "\bTS" ../inputs/input5.txt | egrep "5SS" | egrep "0$"
	# egrep "\bTS" ../inputs/input5.txt | egrep "S5S" | egrep "O$"
	# egrep "\bTS" ../inputs/input5.txt | egrep "S5S" | egrep "0$"
	# egrep "\bTS" ../inputs/input5.txt | egrep "SS5" | egrep "O$"
	# egrep "\bTS" ../inputs/input5.txt | egrep "SS5" | egrep "0$"
